/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clock1;

import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author HP
 */
public class NewJFrame extends javax.swing.JFrame {
int timerun=0;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        new Thread()
        {
            public void run()
            {
                while(timerun==0)
                {
            Calendar c1=new GregorianCalendar();
            int hour=c1.get(Calendar.HOUR);
            int minute=c1.get(Calendar.MINUTE);
            int second=c1.get(Calendar.SECOND);
            int x=c1.get(Calendar.AM_PM);
            String s=hour+":"+minute+":"+second;
            if(x==1)
            {
                s=s+" "+"PM";
            }
            else
                s=s+" "+"AM";
            clo.setText(s);
            }
            }
            
            
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clock");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clo.setFont(new java.awt.Font("DS-Digital", 3, 48)); // NOI18N
        clo.setForeground(new java.awt.Color(0, 0, 204));
        clo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clo.setText("7:45:50");
        clo.setToolTipText("");
        getContentPane().add(clo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 430, 110));

        jLabel1.setFont(new java.awt.Font("DS-Digital", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clock1/Capture.PNG"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 544, 266));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
